<li>
            <div class="before">
              <a href="[field:arcurl/]"><img src="[field:beforeimg function="GetOneImgUrl(@me,1)"/]"/></a>
              <h3>治疗前</h3>
              <p>[field:beforedes/]</p>
            </div>
            <div class="after">
              <a href="[field:arcurl/]"><img src="[field:beforeimg function="GetOneImgUrl(@me,1)"/]"/></a>
              <h3>治疗后</h3>
              <p>[field:afterdes/]</p>
            </div>
            <div class="btn">
              <img src="[field:global.cfg_templets_skin/]/images/anli_btn.jpg"/>
              <a href="javascript:onKST();" class="swt"></a>
              <a href="tel:075525111120" class="tel"></a>
            </div>
          </li>