
<field:beforeimg itemname="治疗前图片" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:beforeimg>

<field:afterimg itemname="治疗后图片" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:afterimg>


<field:beforedes itemname="治疗前描述" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:beforedes>
