<li>
            <div class="img">
              <a href=""><img src="[field:litpic/]"/></a>
            </div>
            <div class="info">
              <h3>[field:title/]<span>／[field:shorttitle/]</span></h3>
              <h4>个人介绍</h4>
              <p>[field:infos/]</p>
            </div>
            <div class="btn">
              <a href="[field:arcurl/]" class="a1">医生简介</a>
              <a href="javascript:onKST();" class="a2">在线咨询</a>
              <a href="javascript:onKST();" class="a3">我要预约</a>
            </div>
          </li>