<li>
            <div class="before">
              <a href="[field:arcurl/]"><img src="[field:beforeimg function="GetOneImgUrl(@me,1)"/]"/></a>
              <h3>治疗前</h3>
              <p>[field:beforedes/]</p>
            </div>
            <div class="after">
              <a href="[field:arcurl/]"><img src="[field:beforeimg function="GetOneImgUrl(@me,1)"/]"/></a>
              <h3>治疗后</h3>
              <p>[field:afterdes/]</p>
            </div>
            <div class="btn">
              <a href="javascript:onKST();" class="swt">在线咨询</a>
              <a href="tel:075525111120" class="tel">电话问诊更快捷：0755-25111120</a>
            </div>
          </li>