<li>
            <div class="before">
              <a href="[field:arcurl/]"><img src="[field:beforeimg function="GetOneImgUrl(@me,1)"/]"/></a>
              <h3>治疗前</h3>
              <p>[field:beforedes/]</p>
            </div>
            <div class="after">
              <a href="[field:arcurl/]"><img src="[field:beforeimg function="GetOneImgUrl(@me,1)"/]"/></a>
              <h3>治疗后</h3>
              <p>[field:afterdes/]</p>
            </div>
          </li>