<?php
$z[0]=Array("global","",28,60);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",135,167);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",559,591);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",669,701);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1543,1575);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",2060,2092);
$z[5][4]['name']="cfg_templets_skin";

?>