<?php
$z[0]=Array("field","",402,424);
$z[0][4]['name']="typename";
$z[1]=Array("global","",427,453);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",498,520);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",563,588);
$z[3][4]['name']="description";
$z[4]=Array("global","",642,674);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",742,774);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",841,873);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",950,987);
$z[7][4]['filename']="header.htm";
$z[8]=Array("global","",1069,1101);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1199,1231);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",1434,1466);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("field","\r\n        \$a=mb_strlen(@me);\r\n        @me=cn_substr(@me,\$a-4);\r\n        ",1489,1615);
$z[11][4]['name']="position";
$z[11][4]['runphp']="yes";
$z[12]=Array("list","\r\n          <li>\r\n            <div class=\"t\">\r\n              <div class=\"img\">\r\n                <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"/></a>\r\n              </div>\r\n              <div class=\"info\">\r\n                <h3>[field:title/]<span>／[field:shorttitle/]</span></h3>\r\n                <h4>个人介绍</h4>\r\n                <p>[field:infos/]</p>\r\n              </div>\r\n            </div>\r\n            <div class=\"btn\">\r\n              <a href=\"[field:arcurl/]\" class=\"a1\">医生简介</a>\r\n              <a href=\"javascript:onKST();\" class=\"a2\">在线咨询</a>\r\n              <a href=\"javascript:onKST();\" class=\"a3\">我要预约</a>\r\n            </div>\r\n          </li>\r\n          ",1696,2433);
$z[12][4]['pagesize']="4";
$z[13]=Array("pagelist","",2514,2580);
$z[13][4]['listitem']="index,end,pre,next,pageno";
$z[13][4]['listsize']="1";
$z[14]=Array("include","",3351,3394);
$z[14][4]['filename']="common_order.htm";
$z[15]=Array("include","",3402,3439);
$z[15][4]['filename']="footer.htm";

?>