<?php
$z[0]=Array("field","",402,424);
$z[0][4]['name']="typename";
$z[1]=Array("global","",427,453);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",498,520);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",563,588);
$z[3][4]['name']="description";
$z[4]=Array("global","",642,674);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",742,774);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",847,884);
$z[6][4]['filename']="header.htm";
$z[7]=Array("include","",892,929);
$z[7][4]['filename']="banner.htm";
$z[8]=Array("global","",983,1015);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("field","\r\n        \$a=mb_strlen(@me);\r\n        @me=cn_substr(@me,\$a-4);\r\n        ",1038,1164);
$z[9][4]['name']="position";
$z[9][4]['runphp']="yes";
$z[10]=Array("list","\r\n          <li><a href=\"[field:arcurl/]\">[field:title/]<span>【阅读全文】</span></a></li>\r\n          ",1843,1987);
$z[10][4]['pagesize']="8";
$z[11]=Array("pagelist","",2068,2134);
$z[11][4]['listitem']="index,end,pre,next,pageno";
$z[11][4]['listsize']="1";
$z[12]=Array("include","",2905,2948);
$z[12][4]['filename']="common_order.htm";
$z[13]=Array("include","",2956,2993);
$z[13][4]['filename']="footer.htm";

?>