<?php
$z[0]=Array("field","",402,424);
$z[0][4]['name']="typename";
$z[1]=Array("global","",427,453);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",498,520);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",563,588);
$z[3][4]['name']="description";
$z[4]=Array("global","",642,674);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",742,774);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",841,873);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",951,988);
$z[7][4]['filename']="header.htm";
$z[8]=Array("include","",996,1033);
$z[8][4]['filename']="banner.htm";
$z[9]=Array("global","",1087,1119);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("field","\r\n        \$a=mb_strlen(@me);\r\n        @me=cn_substr(@me,\$a-4);\r\n        ",1142,1268);
$z[10][4]['name']="position";
$z[10][4]['runphp']="yes";
$z[11]=Array("list","\r\n          <li>\r\n            <div class=\"img\">\r\n              <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"/></a>\r\n            </div>\r\n            <div class=\"info\">\r\n              <h3>[field:title/]</h3>\r\n              <p>[field:infos/]<a href=\"[field:arcurl/]\">【详细】</a></p>\r\n            </div>\r\n          </li>\r\n          ",1350,1740);
$z[11][4]['pagesize']="4";
$z[11][4]['infolen']="100";
$z[12]=Array("pagelist","",1821,1887);
$z[12][4]['listitem']="index,end,pre,next,pageno";
$z[12][4]['listsize']="1";
$z[13]=Array("include","",2658,2701);
$z[13][4]['filename']="common_order.htm";
$z[14]=Array("include","",2709,2746);
$z[14][4]['filename']="footer.htm";

?>